spring.application.name=management
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/vet-clinic
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=management
spring.liquibase.enabled=true
